name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['macOS-latest', 'windows-2019', 'ubuntu-16.04']
        kind: ['test']
    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install Deno (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y xclip xsel xvfb --no-install-recommends
          curl -fsSL https://deno.land/x/install/install.sh | sh -s "v0.25.0"
          echo ::add-path::$HOME/.deno/bin:$PATH
          xvfb-run ./test.sh

      - name: Install Deno (mac)
        if: startsWith(matrix.os, 'macOS')
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s "v0.25.0"
          echo ::add-path::$HOME/.deno/bin:$PATH
          deno test --allow-run --allow-net test.ts
  
      - name: Install Deno (windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          iwr https://deno.land/x/install/install.ps1 -useb | iex
          echo ::add-path::$Home\\.deno\\bin
          deno test --allow-run --allow-net test.ts

      - name: Log versions
        run: |
          deno --version
